### ISSUE TITLE
jsdom 11.2.0 requires compromised cryptiles library

### ISSUE THREAD

**Issue by wwoods** [fortes/metalsmith-dom-transform#10]
Hey, thanks for putting this repo up.  I've been using it in a blog template; looks like the jsdom version in the `metalsmith-dom-transform 2.0.0` on npm has a compromised dependency though.  Might want to push an update to NPM if you have time with a more recent jsdom.

**Comment by fortes** [comment]
Thanks for the heads up, I've updated and published https://www.npmjs.com/package/metalsmith-dom-transform

**Comment by wwoods** [comment]
Cool, thanks!
